-- Nonscholastic Supabase database
-- Run this file in Supabase SQL Editor.
-- Safe for the browser: frontend code must use only the publishable key, never a service-role key.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    email text,
    role text not null default 'learner'
        check (role in ('learner', 'educator')),
    bio text,
    profile_image text,
    created_at timestamp with time zone default now()
);

create table if not exists public.courses (
    id bigint generated by default as identity primary key,
    educator_id uuid not null references public.profiles(id) on delete cascade,
    title text not null,
    description text,
    category text,
    level text,
    thumbnail text,
    duration text,
    created_at timestamp with time zone default now()
);

create table if not exists public.lessons (
    id bigint generated by default as identity primary key,
    course_id bigint not null references public.courses(id) on delete cascade,
    title text not null,
    description text,
    video_url text,
    lesson_order integer default 1,
    created_at timestamp with time zone default now()
);

create table if not exists public.enrollments (
    id bigint generated by default as identity primary key,
    learner_id uuid not null references public.profiles(id) on delete cascade,
    course_id bigint not null references public.courses(id) on delete cascade,
    enrolled_at timestamp with time zone default now(),
    unique (learner_id, course_id)
);

create table if not exists public.progress (
    id bigint generated by default as identity primary key,
    learner_id uuid not null references public.profiles(id) on delete cascade,
    lesson_id bigint not null references public.lessons(id) on delete cascade,
    completed boolean default false,
    completed_at timestamp with time zone,
    unique (learner_id, lesson_id)
);

create table if not exists public.saved_courses (
    id bigint generated by default as identity primary key,
    learner_id uuid not null references public.profiles(id) on delete cascade,
    course_id bigint not null references public.courses(id) on delete cascade,
    saved_at timestamp with time zone default now(),
    unique (learner_id, course_id)
);

create table if not exists public.sessions (
    id bigint generated by default as identity primary key,
    educator_id uuid not null references public.profiles(id) on delete cascade,
    course_id bigint references public.courses(id) on delete cascade,
    title text not null,
    description text,
    session_date timestamp with time zone not null,
    meeting_link text,
    created_at timestamp with time zone default now()
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    sender_id uuid not null references public.profiles(id) on delete cascade,
    receiver_id uuid not null references public.profiles(id) on delete cascade,
    message text not null,
    created_at timestamp with time zone default now()
);

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    learner_id uuid not null references public.profiles(id) on delete cascade,
    course_id bigint not null references public.courses(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    comment text,
    created_at timestamp with time zone default now(),
    unique (learner_id, course_id)
);

-- Automatically create a profile after Supabase Auth creates a user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, full_name, email, role)
    values (
        new.id,
        coalesce(new.raw_user_meta_data->>'full_name', ''),
        new.email,
        coalesce(new.raw_user_meta_data->>'role', 'learner')
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row
    execute procedure public.handle_new_user();

-- Enable Row Level Security.
alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.lessons enable row level security;
alter table public.enrollments enable row level security;
alter table public.progress enable row level security;
alter table public.saved_courses enable row level security;
alter table public.sessions enable row level security;
alter table public.messages enable row level security;
alter table public.reviews enable row level security;

-- Re-running the script will not create duplicate policies.
drop policy if exists "profiles_select_authenticated" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "courses_select_authenticated" on public.courses;
drop policy if exists "courses_insert_educator" on public.courses;
drop policy if exists "courses_update_own" on public.courses;
drop policy if exists "courses_delete_own" on public.courses;
drop policy if exists "lessons_select_authenticated" on public.lessons;
drop policy if exists "lessons_insert_own_course" on public.lessons;
drop policy if exists "lessons_update_own_course" on public.lessons;
drop policy if exists "enrollments_select_own" on public.enrollments;
drop policy if exists "enrollments_insert_own" on public.enrollments;
drop policy if exists "enrollments_delete_own" on public.enrollments;
drop policy if exists "progress_select_own" on public.progress;
drop policy if exists "progress_insert_own" on public.progress;
drop policy if exists "progress_update_own" on public.progress;
drop policy if exists "saved_courses_select_own" on public.saved_courses;
drop policy if exists "saved_courses_insert_own" on public.saved_courses;
drop policy if exists "saved_courses_delete_own" on public.saved_courses;
drop policy if exists "sessions_select_authenticated" on public.sessions;
drop policy if exists "sessions_insert_educator" on public.sessions;
drop policy if exists "sessions_update_own" on public.sessions;
drop policy if exists "sessions_delete_own" on public.sessions;
drop policy if exists "messages_select_own" on public.messages;
drop policy if exists "messages_insert_own" on public.messages;
drop policy if exists "reviews_select_authenticated" on public.reviews;
drop policy if exists "reviews_insert_own" on public.reviews;
drop policy if exists "reviews_update_own" on public.reviews;
drop policy if exists "reviews_delete_own" on public.reviews;

create policy "profiles_select_authenticated" on public.profiles
for select to authenticated using (true);
create policy "profiles_update_own" on public.profiles
for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create policy "courses_select_authenticated" on public.courses
for select to authenticated using (true);
create policy "courses_insert_educator" on public.courses
for insert to authenticated with check (
    educator_id = auth.uid() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'educator')
);
create policy "courses_update_own" on public.courses
for update to authenticated using (educator_id = auth.uid()) with check (educator_id = auth.uid());
create policy "courses_delete_own" on public.courses
for delete to authenticated using (educator_id = auth.uid());

create policy "lessons_select_authenticated" on public.lessons
for select to authenticated using (true);
create policy "lessons_insert_own_course" on public.lessons
for insert to authenticated with check (
    exists (select 1 from public.courses c where c.id = course_id and c.educator_id = auth.uid())
);
create policy "lessons_update_own_course" on public.lessons
for update to authenticated using (
    exists (select 1 from public.courses c where c.id = course_id and c.educator_id = auth.uid())
) with check (
    exists (select 1 from public.courses c where c.id = course_id and c.educator_id = auth.uid())
);

create policy "enrollments_select_own" on public.enrollments
for select to authenticated using (learner_id = auth.uid());
create policy "enrollments_insert_own" on public.enrollments
for insert to authenticated with check (learner_id = auth.uid());
create policy "enrollments_delete_own" on public.enrollments
for delete to authenticated using (learner_id = auth.uid());

create policy "progress_select_own" on public.progress
for select to authenticated using (learner_id = auth.uid());
create policy "progress_insert_own" on public.progress
for insert to authenticated with check (learner_id = auth.uid());
create policy "progress_update_own" on public.progress
for update to authenticated using (learner_id = auth.uid()) with check (learner_id = auth.uid());

create policy "saved_courses_select_own" on public.saved_courses
for select to authenticated using (learner_id = auth.uid());
create policy "saved_courses_insert_own" on public.saved_courses
for insert to authenticated with check (learner_id = auth.uid());
create policy "saved_courses_delete_own" on public.saved_courses
for delete to authenticated using (learner_id = auth.uid());

create policy "sessions_select_authenticated" on public.sessions
for select to authenticated using (true);
create policy "sessions_insert_educator" on public.sessions
for insert to authenticated with check (
    educator_id = auth.uid() and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'educator')
);
create policy "sessions_update_own" on public.sessions
for update to authenticated using (educator_id = auth.uid()) with check (educator_id = auth.uid());
create policy "sessions_delete_own" on public.sessions
for delete to authenticated using (educator_id = auth.uid());

create policy "messages_select_own" on public.messages
for select to authenticated using (sender_id = auth.uid() or receiver_id = auth.uid());
create policy "messages_insert_own" on public.messages
for insert to authenticated with check (sender_id = auth.uid());

create policy "reviews_select_authenticated" on public.reviews
for select to authenticated using (true);
create policy "reviews_insert_own" on public.reviews
for insert to authenticated with check (learner_id = auth.uid());
create policy "reviews_update_own" on public.reviews
for update to authenticated using (learner_id = auth.uid()) with check (learner_id = auth.uid());
create policy "reviews_delete_own" on public.reviews
for delete to authenticated using (learner_id = auth.uid());
